name: Ruby

on:
  pull_request:
    branches:
    - master
    
jobs:
  run_spec:
    name: Run spec

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1 
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1 
        with:
          ruby-version: 2.6.x

    services:
      postgres:
        image: postgres:10.3
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    - name: Setup Database
      run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
      env:
        RAILS_ENV: test
    
    - name: Test with Rspec
      env:
        RAILS_ENV: test
        DATABASE_URL: postgresql://postgres@localhost:5432/postgres?encoding=utf8&pool=5&timeout=5000
      run: |
        gem install bundler
        bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
        bundle exec rspec
