name: Ruby

on:
  pull_request:
    branches:
    - master
    
jobs:
  run_spec:
    name: Run spec

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:10.3
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1 
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1 
        with:
          ruby-version: 2.6.x

      - name: Setup bundler
        run: gem install bundler

      - name: bundle install
        run: |
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
            cp config/database.ci.yml config/database.yml
            bundle exec rails db:create
            bundle exec rails db:migrate
        env:
          RAILS_ENV: test
    
      - name: Test with Rspec
        env:
          RAILS_ENV: test
          DA TABASE_URL: postgresql://postgres@localhost:5432/postgres?encoding=utf8&pool=5&timeout=5000
        run: |
          bundle exec rspec
